import axios from 'axios';
import { getCsrfToken, installCsrfTokenRefresh, refreshCsrfToken } from './csrf';

axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
axios.defaults.withCredentials = true;
axios.defaults.xsrfCookieName = 'XSRF-TOKEN';
axios.defaults.xsrfHeaderName = 'X-XSRF-TOKEN';

installCsrfTokenRefresh();

const applyCsrfToken = (config) => {
    const token = getCsrfToken();
    if (token !== '') {
        config.headers = config.headers || {};
        config.headers['X-CSRF-TOKEN'] = token;
    }

    return config;
};

axios.interceptors.request.use((config) => applyCsrfToken(config));

// A 419 here almost never means "the user must log in again" — it means the
// token this tab was holding had gone stale (frozen mobile tab, session swept,
// token regenerated by a login in another tab). Fetch a live token and replay
// the request once; only a genuinely logged-out user falls through to the
// server's redirect.
axios.interceptors.response.use(
    (response) => response,
    async (error) => {
        const { response, config } = error || {};

        if (response?.status !== 419 || !config || config.__csrfRetried) {
            return Promise.reject(error);
        }

        config.__csrfRetried = true;

        const token = await refreshCsrfToken({ force: true });
        if (!token) {
            return Promise.reject(error);
        }

        config.headers = config.headers || {};
        config.headers['X-CSRF-TOKEN'] = token;

        return axios.request(config);
    }
);

export default axios;
