<?php

return [
    'defaults' => [
        'company_name' => env('APP_NAME', 'MyApptimatic'),
        'company_email' => 'hello@example.com',
        'pay_to_text' => 'MyApptimatic',
        'company_logo_path' => null,
        'company_favicon_path' => null,
        'cron_token' => env('CRON_TOKEN'),
        'billing_last_run_at' => null,
        'billing_last_started_at' => null,
        'billing_last_status' => null,
        'billing_last_error' => null,
        'currency' => 'USD',
        'invoice_generation_days' => 7,
        'invoice_due_days' => 7,
        'grace_period_days' => 0,
        'late_fee_days' => 1,
        'late_fee_type' => 'fixed',
        'late_fee_amount' => '0.00',
        'payment_reminder_emails' => false,
        'invoice_unpaid_reminder_days' => 0,
        'first_overdue_reminder_days' => 1,
        'second_overdue_reminder_days' => 2,
        'third_overdue_reminder_days' => 3,
        'enable_suspension' => false,
        'suspend_days' => 3,
        'send_suspension_email' => false,
        'enable_unsuspension' => true,
        'send_unsuspension_email' => false,
        'enable_termination' => false,
        'termination_days' => 30,
        'overage_billing_mode' => 'last_day_separate',
        'change_invoice_status_on_reversal' => false,
        'change_due_dates_on_reversal' => false,
        'enable_auto_cancellation' => false,
        'auto_cancellation_days' => 0,
        'auto_bind_domains' => true,
        'payment_instructions' => 'Contact support to arrange payment.',
    ],
];
