<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $subject ?? $companyName ?? config('app.name') }}</title>
</head>
<body style="margin:0;padding:0;background-color:#f4f6fb;">
<center>
    <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" id="bodyTable" style="background-color:#f4f6fb;">
        <tbody>
        <tr>
            <td align="center" valign="top" id="bodyCell" style="padding:24px 12px;">
                <table border="0" cellpadding="0" cellspacing="0" id="templateContainer" width="600" style="width:600px;max-width:600px;background-color:#ffffff;border:1px solid #e2e8f0;">
                    <tbody>
                    <tr>
                        <td align="center" valign="top">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateHeader">
                                <tbody>
                                <tr>
                                    <td valign="top" style="padding:20px 20px 0 20px;text-align:center;">
                                        @if(!empty($logoUrl))
                                            <img src="{{ $logoUrl }}" alt="{{ $companyName }}" style="max-width:240px;height:auto;display:block;margin:0 auto;">
                                        @else
                                            <div style="font-family:Arial, sans-serif;font-size:20px;font-weight:bold;color:#0f172a;">
                                                {{ $companyName ?? config('app.name') }}
                                            </div>
                                        @endif
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="top">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateBody">
                                <tbody>
                                <tr>
                                    <td valign="top" style="padding:20px;font-family:Arial, sans-serif;font-size:14px;line-height:1.6;color:#334155;">
                                        @yield('content')
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" valign="top">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateFooter">
                                <tbody>
                                <tr>
                                    <td valign="top" style="padding:16px 20px 24px 20px;text-align:center;font-family:Arial, sans-serif;font-size:12px;color:#94a3b8;">
                                        This notification was automatically generated by {{ $companyName ?? config('app.name') }}.<br>
                                        @php
                                            $portal = $portalUrl ?? config('app.url');
                                            $loginUrl = $portalLoginUrl ?? null;
                                            $loginLabel = $portalLoginLabel ?? 'log in to the portal';
                                        @endphp
                                        <a href="{{ $portal }}" style="color:#64748b;text-decoration:none;">{{ $portal }}</a>
                                        @if($loginUrl)
                                            <span style="color:#cbd5f5;"> | </span>
                                            <a href="{{ $loginUrl }}" style="color:#64748b;text-decoration:none;">{{ $loginLabel }}</a>
                                        @endif
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        </tbody>
    </table>
</center>
</body>
</html>
